#!/bin/bash
# Restore Script for Vibration and Acoustics Lab

# Restore Script restores the backup of the data used by the lab.
# Since there is no data being used by Vibration and Acoustics Lab, 
# the script does nothing. 

# Usage of the script

# To use restore script, run the command
# ./scripts/restore
